package constants

const (
	AuditLoginSucceeded               = "identity.login_succeeded"
	AuditLoginFailed                  = "identity.login_failed"
	AuditRegistryAuthFailed           = "identity.registry_auth_failed"
	AuditUserCreated                  = "identity.user_created"
	AuditUserPromotedToSystemAdmin    = "identity.user_promoted_to_system_admin"
	AuditUserPromotedToSystemViewer   = "identity.user_promoted_to_system_viewer"
	AuditUserDisabled                 = "identity.user_disabled"
	AuditServiceAccountCreated        = "identity.service_account_created"
	AuditServiceAccountDisabled       = "identity.service_account_disabled"
	AuditAccessKeyCreated             = "identity.access_key_created"
	AuditAccessKeyRevoked             = "identity.access_key_revoked"
	AuditProjectCreated               = "projects.project_created"
	AuditProjectDeleteRequested       = "projects.project_delete_requested"
	AuditProjectDeleted               = "projects.project_deleted"
	AuditMembershipUpserted           = "projects.membership_upserted"
	AuditMembershipRemoved            = "projects.membership_removed"
	AuditUserPasswordChanged          = "identity.user_password_changed"
	AuditUserPasswordResetLinkCreated = "identity.user_password_reset_link_created"
	AuditUserPasswordResetCompleted   = "identity.user_password_reset_completed"
	AuditRestoreCompleted             = "platform.restore_completed"
	AuditBackupCreated                = "platform.backup_created"
	AuditBackupDeleteRequested        = "platform.backup_delete_requested"
	AuditBackupDeleted                = "platform.backup_deleted"

	AuditLifecyclePreviewCreated   = "registry.lifecycle_preview_created"
	AuditLifecycleRunStarted       = "registry.lifecycle_run_started"
	AuditLifecycleItemDeleted      = "registry.lifecycle_item_deleted"
	AuditLifecycleItemSkipped      = "registry.lifecycle_item_skipped"
	AuditLifecycleItemFailed       = "registry.lifecycle_item_failed"
	AuditLifecycleRunCompleted     = "registry.lifecycle_run_completed"
	AuditLifecycleRunFailed        = "registry.lifecycle_run_failed"
	AuditRepositoryCreatedFromPush = "registry.repository_created_from_push"
	AuditRepositoryPoliciesUpdated = "registry.repository_policies_updated"
	AuditRepositoryArchived        = "registry.repository_archived"
	AuditRepositoryRemoved         = "registry.repository_removed"
	AuditArtifactDeletionStarted   = "registry.artifact_deletion_started"
	AuditArtifactDeletionCompleted = "registry.artifact_deletion_completed"
	AuditArtifactDeletionFailed    = "registry.artifact_deletion_failed"

	AuditResourceRepository       = "registry_repository"
	AuditResourceArtifactDeletion = "artifact_deletion"
	AuditResourceLifecycleRun     = "lifecycle_run"
	AuditResourceUser             = "user"
	AuditResourceAuthentication   = "authentication"
	AuditResourceServiceAccount   = "service_account"
	AuditResourceProject          = "project"
	AuditResourceMembership       = "membership"
	AuditResourceBackup           = "backup"
)
